name: Update README with Projects

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:  # Allows manual triggering
permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update Projects in README
        run: |
          # Get the updated list of projects
          new_content=$(curl -s "https://api.github.com/users/YOUR_USERNAME/repos?per_page=100" | 
            jq -r '.[] | "- [" + .name + "](" + .html_url + ")"')
          
          # Replace content between the markers in README.md
          sed -i '/<!-- START PROJECTS -->/,/<!-- END PROJECTS -->/c\<!-- START PROJECTS -->\'"$new_content"'\<!-- END PROJECTS -->' README.md

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Updated project list" || echo "No changes to commit"
          git push
